//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string IDADMIN { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
    }
}
