//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.DetalleFacturas = new HashSet<DetalleFactura>();
        }
    
        public string IDPRODUCTO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public int IDTIPOPRODUCTO { get; set; }
        public byte[] FOTO { get; set; }
        public decimal PRECIOUNITARIO { get; set; }
        public int CANTIDADDISPONIBLE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
