//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProducto
    {
        public TipoProducto()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int IDTIPOPRODUCTO { get; set; }
        public string NOMBRETIPOPRODUCTO { get; set; }
    
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
